# Generated by Django 2.0 on 2017-12-21 02:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('joke_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('body', models.CharField(max_length=2000)),
                ('ups', models.IntegerField()),
                ('downs', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'reddit_jokes',
            },
        ),
    ]
